// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $messageno = $.ScalarType<"std::number", number>;
const messageno: $.scalarTypeWithConstructor<_std.$number, string> = $.makeType<$.scalarTypeWithConstructor<_std.$number, string>>(_.spec, "6e2d5430-90f9-11ef-909d-8527183427f9", _.syntax.literal);

export type $AccountλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "avatar": $.PropertyDesc<_std.$bytes, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "password": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "joined": $.LinkDesc<$GroupServer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<postedby[is Messages]": $.LinkDesc<$Messages, $.Cardinality.Many, {}, false, false,  false, false>;
  "<postedby": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Account = $.ObjectType<"default::Account", $AccountλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Account = $.makeType<$Account>(_.spec, "6e2af3f6-90f9-11ef-8a7e-098ff2d81a1e", _.syntax.literal);

const Account: $.$expr_PathNode<$.TypeSet<$Account, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Account, $.Cardinality.Many), null);

export type $GroupServerλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "messages": $.LinkDesc<$Messages, $.Cardinality.Many, {}, false, false,  false, false>;
  "image": $.PropertyDesc<_std.$bytes, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<joined[is Account]": $.LinkDesc<$Account, $.Cardinality.Many, {}, false, false,  false, false>;
  "<joined": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $GroupServer = $.ObjectType<"default::GroupServer", $GroupServerλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $GroupServer = $.makeType<$GroupServer>(_.spec, "6e30de93-90f9-11ef-831a-6de9356c9ef8", _.syntax.literal);

const GroupServer: $.$expr_PathNode<$.TypeSet<$GroupServer, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($GroupServer, $.Cardinality.Many), null);

export type $MessagesλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "postedby": $.LinkDesc<$Account, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "data": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "position": $.PropertyDesc<$messageno, $.Cardinality.AtMostOne, true, false, false, true>;
  "<messages[is GroupServer]": $.LinkDesc<$GroupServer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<messages": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Messages = $.ObjectType<"default::Messages", $MessagesλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {position: {__element__: $messageno, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Messages = $.makeType<$Messages>(_.spec, "6e2d68f2-90f9-11ef-9dc0-1bf22ba5fe3b", _.syntax.literal);

const Messages: $.$expr_PathNode<$.TypeSet<$Messages, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Messages, $.Cardinality.Many), null);



export { messageno, $Account, Account, $GroupServer, GroupServer, $Messages, Messages };

type __defaultExports = {
  "messageno": typeof messageno;
  "Account": typeof Account;
  "GroupServer": typeof GroupServer;
  "Messages": typeof Messages
};
const __defaultExports: __defaultExports = {
  "messageno": messageno,
  "Account": Account,
  "GroupServer": GroupServer,
  "Messages": Messages
};
export default __defaultExports;
